Topic.create(name: "Appointments")
Topic.create(name: "Career")
Topic.create(name: "Education")
Topic.create(name: "Exercise")
Topic.create(name: "Family")
Topic.create(name: "Goals")
Topic.create(name: "Life")
Topic.create(name: "Menu Planning")
Topic.create(name: "Milestones")
Topic.create(name: "Personal")
Topic.create(name: "Shopping List")
Topic.create(name: "To-Do List")
Topic.create(name: "Other") 